init:
	AWS_PROFILE="terraform-course" terraform init

plan:
	AWS_PROFILE="terraform-course" terraform plan

apply:
	AWS_PROFILE="terraform-course" terraform apply -auto-approve

destroy:
	AWS_PROFILE="terraform-course" terraform destroy -auto-approve

state_list:
	AWS_PROFILE="terraform-course" terraform state list
